# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

variables:
  - group: vg-apio-tfi

steps:
- bash: bash scripts/EstablishEnv.sh
  displayName: 'Establish the Environment'
  env:
    conntoken: $(databricks-token)
- bash: bash scripts/BuildTest.sh
  displayName: 'Build and Run the Tests'
- bash: bash scripts/DeployDatabricks.sh
  displayName: 'Deploy to Databricks on Azure'
  env:
    conntoken: $(databricks-token)